version: '3.8'

services:
  prometheus:
    image: prom/prometheus:${PROM_VERSION}
    container_name: prometheus
    #user: "nobody"
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
     # - ./prometheus_alerts.yml:/etc/prometheus/alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    user: "472"
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    secrets:
      - gf_security_admin_user
      - gf_security_admin_password
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/gf_security_admin_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/gf_security_admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    networks:
      - monitoring
    ports:
      - "3000:3000"

volumes:
  prometheus_data:
    driver: local

secrets:
  gf_security_admin_user:
    file: ./grafana_user.txt  # File containing the Grafana admin username
  gf_security_admin_password:
    file: ./grafana_password.txt  # File containing the Grafana admin password

networks:
  monitoring:
    driver: bridge