version: "3.8"

services:
  prometheus:
    image: prom/prometheus:${PROM_VERSION}
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Add this line for data persistence
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    secrets:
      - gf_security_admin_user
      - gf_security_admin_password
    environment:
      - GF_SECURITY_ADMIN_USER_FILE=/run/secrets/gf_security_admin_user
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/gf_security_admin_password

volumes:
  prometheus_data:  # Define the volume for Prometheus data

secrets:
  gf_security_admin_user:
    file: ./grafana_user.txt  # File containing the Grafana admin username
  gf_security_admin_password:
    file: ./grafana_password.txt  # File containing the Grafana admin password