global:
 scrape_interval: 5s
 evaluation_interval: 15s
scrape_configs:
 - job_name: 'kafka'
   metrics_path: /metrics
   static_configs:
    - targets:
      - node1:8090   # Kafka 1 
      - node2:8090   # Kafka 2 
      - node3:8090   # Kafka 3 
